### ISSUE TITLE
Can't create handler inside thread that has not called Looper.prepare()

### ISSUE THREAD

**Issue by cvoronin** [ThreadsMobileLib/threads-sdk-android#1]
Версия 2.33.1
При инициализации и отображении чат-фрагмента в логе устройства вижу стектрейс, см. ниже.
Приложение не крашится, история чата корректно загружается. 

```
03-28 21:55:12.419 27022-27791/ru.simpls.brs2.mobbank W/System.err: java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
        at android.os.Handler.<init>(Handler.java:203)
        at android.os.Handler.<init>(Handler.java:117)
        at com.pushserver.android.PushNetworkManager$AsyncJob.<init>(PushNetworkManager.java:229)
        at com.pushserver.android.PushNetworkApi$6.<init>(PushNetworkApi.java:337)
        at com.pushserver.android.PushNetworkApi.sendMessageAsync(PushNetworkApi.java:336)
        at com.pushserver.android.PushController.sendMessageAsync(PushController.java:321)
        at im.threads.utils.Transport.sendMessageMFMSAsync(Transport.java:53)
03-28 21:55:12.420 27022-27791/ru.simpls.brs2.mobbank W/System.err:     at im.threads.controllers.ChatController$7.run(ChatController.java:483)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
03-28 21:55:12.429 27022-27791/ru.simpls.brs2.mobbank W/System.err: java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
        at android.os.Handler.<init>(Handler.java:203)
        at android.os.Handler.<init>(Handler.java:117)
        at com.pushserver.android.PushNetworkManager$AsyncJob.<init>(PushNetworkManager.java:229)
        at com.pushserver.android.PushNetworkApi$6.<init>(PushNetworkApi.java:337)
        at com.pushserver.android.PushNetworkApi.sendMessageAsync(PushNetworkApi.java:336)
        at com.pushserver.android.PushController.sendMessageAsync(PushController.java:321)
        at im.threads.utils.Transport.sendMessageMFMSAsync(Transport.java:53)
        at im.threads.controllers.ChatController$7.run(ChatController.java:489)
03-28 21:55:12.430 27022-27791/ru.simpls.brs2.mobbank W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by Luten** [comment]
Fixed in 2.43.0
