### ISSUE TITLE
Падение демо-приложения при попытке открытия вкладки "Чат"

### ISSUE THREAD

**Issue by N1ckname** [ThreadsMobileLib/threads-sdk-android#7]
При выборе вкладки "Чат" в BottomNavigationActivity приложение завершает работу с исключением android.view.InflateException. Для восстановления корректной работы приложения, необходимо переименовать app/src/main/Assets в app/src/main/assets
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.sequenia.appwithchat.polarbear, PID: 8701
    android.view.InflateException: Binary XML file line #16 in com.sequenia.appwithchat.polarbear:layout/fragment_chat: Binary XML file line #16 in com.sequenia.appwithchat.polarbear:layout/fragment_chat: Error inflating class im.threads.internal.widget.CustomFontButton
    Caused by: android.view.InflateException: Binary XML file line #16 in com.sequenia.appwithchat.polarbear:layout/fragment_chat: Error inflating class im.threads.internal.widget.CustomFontButton
    Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:854)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1006)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:682)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
        at androidx.databinding.DataBindingUtil.inflate(DataBindingUtil.java:126)
        at androidx.databinding.DataBindingUtil.inflate(DataBindingUtil.java:95)
        at im.threads.view.ChatFragment.onCreateView(ChatFragment.java:183)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2698)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:320)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1187)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1497)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
        at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2169)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1992)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1947)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1849)
        at androidx.fragment.app.FragmentManager.executePendingTransactions(FragmentManager.java:489)
        at im.threads.android.ui.BottomNavigationActivity.selectTab(BottomNavigationActivity.java:207)
        at im.threads.android.ui.BottomNavigationActivity.lambda$new$0$BottomNavigationActivity(BottomNavigationActivity.java:117)
        at im.threads.android.ui.-$$Lambda$BottomNavigationActivity$5lanH9ucy2Us9WExS80AzcNYNUk.onNavigationItemSelected(Unknown Source:2)
        at com.google.android.material.bottomnavigation.BottomNavigationView$1.onMenuItemSelected(BottomNavigationView.java:243)
        at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:840)
        at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
        at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:991)
        at com.google.android.material.bottomnavigation.BottomNavigationMenuView$1.onClick(BottomNavigationMenuView.java:127)
        at android.view.View.performClick(View.java:7259)
        at android.view.View.performClickInternal(View.java:7236)
        at android.view.View.access$3600(View.java:801)
        at android.view.View$PerformClick.run(View.java:27892)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
E/AndroidRuntime: Caused by: java.lang.RuntimeException: Font asset not found fonts/lato-regular.ttf
        at android.graphics.Typeface.createFromAsset(Typeface.java:965)
        at im.threads.internal.widget.CustomFontButton.setTypefaceView(CustomFontButton.java:32)
        at im.threads.internal.widget.CustomFontButton.<init>(CustomFontButton.java:26)
        	... 43 more
```

**Comment by valeh962** [comment]
it did not solved my issue
please help...
